services:
  app:
    build: .
    container_name: app # jika tidak menggunakan container_name, Docker akan membuat nama unik sesuai dengan nama direktori
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: db 
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4 
    container_name: pgadmin 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5430:80 
    depends_on: # This ensures pgAdmin starts after the database is ready
      - db # Ensure pgAdmin waits for the db service

volumes:
  pg_data: