name: Deploy to production

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # The type of runner that the job will run on 
    # delpoy di jalankan di satu vm baru setiap kali ada push ke main pake ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      # Checkout/download the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Deploy to the server using SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        # Ensure you have set the following secrets in your GitHub repository:
        # SSH_HOST, SSH_USERNAME, SSH_PRIVATE_KEY
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /home/nurulid/app-dockerc/fastapi-dockerc/bin
            ./update.sh
          # Sesuaikan dengan path di server